### ISSUE TITLE
Cannot download a package with dependencies

### ISSUE THREAD

**Issue by KMamedoff** [bamtan/Cyder3.0#1]
It always show an error and just downloads the main package. Never downloads the dependencies. 
![screen shot 2017-01-31 at 02 48 11](https://cloud.githubusercontent.com/assets/5307981/22445205/c504596c-e75f-11e6-9d2c-895975fefb4b.png)

**Comment by bamtan** [comment]
Download Cyder 3.0 beta (0.2.1.0) from [here](https://iosgods.com/topic/33906-release-cyder-30-download-cydia-deb-files-on-your-windows-desktop/).

**Comment by KMamedoff** [comment]
I don't know if I installed Cyder 3.0 beta (0.2.1.0) but it was on the first post of the topic. The problem still persists.

**Comment by bamtan** [comment]
I'm not the coder for this, just hosting it on GitHub. You'd have to contact the creator, WarL0ck, from the link in my previous reply.
